<a href="https://colab.research.google.com/github/denisegonzaa/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Laboratory 6: Matrix Operation

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the 

$$A = \begin{bmatrix} 3 & 2 & 6\\5 & -2 & 2\\ 1 & 0 & 7\end{bmatrix} $$


$$A^T = \begin{bmatrix} 3 & 5 & 1\\2 & -2 & 0 \\ 6 & 2 & 7\end{bmatrix} $$

This can now be achieved

In [3]:
A = np.array ([
    [3 , 2, 6],
    [5 , -2, 2],
    [1, 0, 7]
])

In [4]:
AT1 = np.transpose(A)
AT1

array([[ 3,  5,  1],
       [ 2, -2,  0],
       [ 6,  2,  7]])

In [5]:
AT2 = A.T
AT2

array([[ 3,  5,  1],
       [ 2, -2,  0],
       [ 6,  2,  7]])

In [6]:
np.array_equiv(AT1, AT2)

True

In [7]:
B = np.array([
    [1,4,8,5],
    [1,2,0,4],
])
B.shape

(2, 4)

In [8]:
np.transpose(B).shape

(4, 2)

In [9]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [10]:
## Try out your code here.
Z=np.array([
    [5,0,4],
    [9,2,1]        
])
Z.shape

(2, 3)

In [11]:
np.transpose(Z).shape

(3, 2)

In [12]:
Z.T.shape

(3, 2)

In [13]:
ZT = Z.T
ZT

array([[5, 9],
       [0, 2],
       [4, 1]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [14]:
X = np.array([
    [6,1],
    [0,4]
])
Y = np.array([
    [-9,4],
    [0,1]
])

In [15]:
np.array_equiv(X, Y)

False

In [16]:
np.dot(X,Y)

array([[-54,  25],
       [  0,   4]])

In [17]:
X.dot(Y)

array([[-54,  25],
       [  0,   4]])

In [18]:
X @ Y

array([[-54,  25],
       [  0,   4]])

In [19]:
np.matmul(X,Y)

array([[-54,  25],
       [  0,   4]])

In [20]:
D = np.array([
    [0,5,6],
    [9,2,1],
    [11,2,7]
])
E = np.array([
    [-1,1,2],
    [1,-1,4],
    [4,1,2]
])

In [21]:
D @ E

array([[29,  1, 32],
       [-3,  8, 28],
       [19, 16, 44]])

In [22]:
D.dot(E)

array([[29,  1, 32],
       [-3,  8, 28],
       [19, 16, 44]])

In [23]:
np.matmul(D, E)

array([[29,  1, 32],
       [-3,  8, 28],
       [19, 16, 44]])

In [24]:
np.dot(D, E)

array([[29,  1, 32],
       [-3,  8, 28],
       [19, 16, 44]])



In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [25]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [26]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [27]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [28]:
A @ B

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [29]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [30]:
ERI = np.array([
    [1,4,8,5]
])
EXO = np.array([
    [1,2,0,-4]
])
print(ERI.shape)
print(EXO.shape)

(1, 4)
(1, 4)


In [31]:
EXO.T @ ERI

array([[  1,   4,   8,   5],
       [  2,   8,  16,  10],
       [  0,   0,   0,   0],
       [ -4, -16, -32, -20]])

In [32]:
ERI @ EXO.T

array([[-11]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [33]:
H = np.array([
    [3,2,6],
    [5,2,2],
    [1,0,7]
])
B = np.array([
    [5,0,6],
    [9,2,1],
    [11,2,7]
])
M = np.array([
    [1,1,2],
    [1,1,4],
    [4,1,2]
])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
H.dot(np.eye(3))

array([[3., 2., 6.],
       [5., 2., 2.],
       [1., 0., 7.]])

In [36]:
np.array_equal(H@B, B@H)

False

In [37]:
L = H @ (B @ M)
L

array([[363, 177, 386],
       [257, 119, 254],
       [316, 151, 330]])

In [38]:
P = (H @ B) @ M
P

array([[363, 177, 386],
       [257, 119, 254],
       [316, 151, 330]])

In [39]:
np.array_equal(L, H)

False

In [40]:
np.array_equiv(L, P)

True

In [41]:
np.eye(H)

TypeError: ignored

In [42]:
H @ L

array([[3499, 1675, 3646],
       [2961, 1425, 3098],
       [2575, 1234, 2696]])

In [43]:
z_mat = np.zeros(H.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
a_dot_z = H.dot(np.zeros(H.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.array_equal(a_dot_z,z_mat)

True

In [46]:
null_mat = np.empty(H.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [47]:
F = np.array([
    [1,4],
    [0,2]
])
np.linalg.det(F)

2.0

In [48]:
C = np.array([
              [1, 5, 2],
              [3, -1 ,-1],
              [0, -2, 1]
])
np.linalg.det(C)

-30.000000000000014

In [49]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
C = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

36.000000000000014

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [50]:
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [2, 0, 2]
])

np.array(X @np.linalg.inv(X), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
S = np.array([
              [2, 5, 9, 0],
              [1, 9, 2, 9],
              [2, 4, 5, 9],
              [1, 1, 0, 0]
])
R = np.linalg.inv(S)
R

array([[-0.04761905, -0.14285714,  0.14285714,  0.95238095],
       [ 0.04761905,  0.14285714, -0.14285714,  0.04761905],
       [ 0.0952381 , -0.04761905,  0.04761905, -0.23809524],
       [-0.06349206, -0.00529101,  0.11640212, -0.1005291 ]])

In [52]:
S @ R

array([[ 1.00000000e+00, -6.93889390e-17,  6.93889390e-17,
         0.00000000e+00],
       [ 1.24900090e-16,  1.00000000e+00,  1.38777878e-17,
         1.38777878e-16],
       [ 1.24900090e-16, -6.07153217e-17,  1.00000000e+00,
         1.38777878e-16],
       [-7.63278329e-17,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [53]:
## And now let's test your skills in solving a matrix with high dimensions:
U = np.array([
    [12,3,8,-2,0,9],
    [9,4,1,63,1,4],
    [4,14,94,-2,20,12],
    [75,42,98,2,78,4],
    [5,32,14,90,15,4],
    [23,18,-5,0,11,6]
])
U_inv = np.linalg.inv(U)
np.array(U @ U_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [54]:
rar = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
skrt = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = rar @ skrt.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [61]:
E = np.array([
    [1, 0, -1, 3],
    [2, 0, -5, 5],
    [9, 8, 3, 5],
    [-6, -1, 0, 4]
])
F = np.array([
    [2, 0, 4, 1],
    [8, 3, -1, -7],
    [8, 5, -3, 4],
    [6, -1, 6, 3]
])

print('Matrix E:')
print(E)
print('Matrix F:')
print(F)

Matrix E:
[[ 1  0 -1  3]
 [ 2  0 -5  5]
 [ 9  8  3  5]
 [-6 -1  0  4]]
Matrix F:
[[ 2  0  4  1]
 [ 8  3 -1 -7]
 [ 8  5 -3  4]
 [ 6 -1  6  3]]


 $A \cdot B \neq B \cdot A$

In [62]:
print('Matrix product EF:')
EF = np.matmul(E,F)
EF

Matrix product EF:


array([[ 12,  -8,  25,   6],
       [ -6, -30,  53,  -3],
       [136,  34,  49, -20],
       [  4,  -7,   1,  13]])

In [63]:
print('Matrix product FE:')
FE = np.matmul(F,E)
FE

Matrix product FE:


array([[ 32,  31,  10,  30],
       [ 47,  -1, -26,   6],
       [-33, -28, -42,  50],
       [ 40,  45,  17,  55]])

In [64]:
np.array_equal(EF, FE)

False

In [65]:
G = np.array([
    [2, 3, -4, 9],
    [2, 2, -2, -2],
    [0, 1, 6, 3],
    [-2, -9, 1, 8]
])
H = np.array([
    [1, 9, 3],
    [2, 3, 2],
    [3, 9, 4],
    [1, 6, 2]
])
I = np.array([
    [2, 4, 6],
    [9, 0, 1],
    [2, 6, 9]
])
GH = np.matmul(G,H)
HI = np.matmul(H,I)

print('Matrix G:')
print(G)
print('Matrix H:')
print(H)
print('Matrix I:')
print(I)

Matrix G:
[[ 2  3 -4  9]
 [ 2  2 -2 -2]
 [ 0  1  6  3]
 [-2 -9  1  8]]
Matrix H:
[[1 9 3]
 [2 3 2]
 [3 9 4]
 [1 6 2]]
Matrix I:
[[2 4 6]
 [9 0 1]
 [2 6 9]]


$A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [66]:
print('Matrix Product (GH)I:')
L = np.matmul(GH,I)
L

Matrix Product (GH)I:


array([[443, 104, 201],
       [-62, -20, -36],
       [785, 284, 501],
       [ 82, -60, -78]])

In [67]:
print('Matrix Product G(HI)')
R = np.matmul(G,HI)
R

Matrix Product G(HI)


array([[443, 104, 201],
       [-62, -20, -36],
       [785, 284, 501],
       [ 82, -60, -78]])

In [68]:
np.array_equal(L, R)

True

In [69]:
J = np.array([-1,3,2])
K = np.array([
    [0, 2, 3],
    [5, 6, 8],
    [2, 3, 1]
    ])
L = np.array([
    [1, 4, 9],
    [8, -1, 0],
    [5, 2, 1]
    ])
JK = np.matmul(J,K)
KL = np.matmul(K,L)
JL = np.matmul(J,L)

print('Matrix J')
print(J)
print('Matrix K:')
print(K)
print('Matrix L:')
print(L) 

Matrix J
[-1  3  2]
Matrix K:
[[0 2 3]
 [5 6 8]
 [2 3 1]]
Matrix L:
[[ 1  4  9]
 [ 8 -1  0]
 [ 5  2  1]]


$A\cdot(B+C) = A\cdot B + A\cdot C$

In [70]:
print('\n')
print('Distributing left multiplication')
print('Matrix Product J*(K + L):')
print(np.matmul(J,K+L))
print('Matrix Product (JK + JL):')
DL = JK+JL
DL




Distributing left multiplication
Matrix Product J*(K + L):
[52 19 16]
Matrix Product (JK + JL):


array([52, 19, 16])

In [71]:
D = J @ (K+L)
D

array([52, 19, 16])

In [72]:
np.array_equal(DL, D)

True

$(A+B)\cdot C = A\cdot C + B\cdot C$

In [73]:
print('Distributing right multiplication')
print('Matrix Product (J + K)*L:')
print(np.matmul(J+K,L))
print('Matrix Product (JL + KL):')
DR = JL + KL
DR

Distributing right multiplication
Matrix Product (J + K)*L:
[[ 64   1  -4]
 [126  27  46]
 [ 64   4  12]]
Matrix Product (JL + KL):


array([[ 64,   1,  -4],
       [126,  27,  46],
       [ 64,   4,  12]])

In [74]:
E = (J+K) @L
E

array([[ 64,   1,  -4],
       [126,  27,  46],
       [ 64,   4,  12]])

In [75]:
np.array_equal(DR, E)

True

In [76]:
N = np.array([
      [-1,-2,-3],
      [1, 2, -2],
      [0, 1, 2]
      ])
N

array([[-1, -2, -3],
       [ 1,  2, -2],
       [ 0,  1,  2]])

$A\cdot I = A$

In [77]:
NI = np.identity(3)
NI
O =N@NI
O

array([[-1., -2., -3.],
       [ 1.,  2., -2.],
       [ 0.,  1.,  2.]])

 $A\cdot \emptyset = \emptyset$ 

In [78]:
NZ = N.dot(np.zeros(N.shape))
NZ


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
P = N@NZ
P

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.array_equal(NZ,P)

True

## Conclusion

Through this laboratory activity, it proved that it is easier to solve multiplication of matrices through Google Collab than manually solving it. With inputting codes to our matrices, the program itself will automatically solve it  by clicking “Run”. Nonetheless, codes are a bit sensitive when inputted – not to mention some might be the same but will have a different outcome – one will find it convenient to learn and apply the codes every time they encounter matrix problems. Also, the rules and properties for matrix multiplication were guides for encoding as well so that one will not be confused on what codes are appropriate to apply. Learning through Google Colab requires patience yet it is interacting and interesting in some ways – like if one was to apply future calculations related to matrix multiplications such as inverse, determinants, dot product, and many more. 