<a href="https://colab.research.google.com/github/denisegonzaa/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3: Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have ***A*** , ***B***, and ***C*** as system of equation.


$$
A = \left\{
    \begin{array}\
        s + h \\ 
        5s - 22h
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        d+k+s \\ 
        d -12k -93s \\
        -7d + 26k +22s
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      y-3u+2j-7i \\
      4y-u-5j+i \\
      9y-u+6j-4i
    \end{array}
\right. \\
$$

We could see that ***A*** is a system of 2 equations with 2 parameters. While ***B*** is a system of 3 equations with 3 parameters. With ***C*** is a system of 3 equations with 4 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 5 & {-22}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -12 & -93 \\ -7 & 26 & 22\end{bmatrix}\\
C=\begin{bmatrix} 1 & -3 & 2 & -7 \\ 4 & -1 & -5 & 1 \\ 9 & -1 & 6 & -4\end{bmatrix}\\
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while  stands for the number of columns. <br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using **shape**, **dimensions**, and **size** attributes, we'll use them to analyze these matrices.

In [2]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [3]:
## Declaring a 2 x 2 matrix
A = np.array([
    [4, 8],
    [2, 7]
])
describe_mat(A)

Matrix:
[[4 8]
 [2 7]]

Shape:	(2, 2)
Rank:	2



In [4]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [5]:
## Declaring a 3 x 2 matrix
B = np.array([
    [1, 4],
    [8, 5],
    [2, 7]
])
describe_mat(B)

Matrix:
[[1 4]
 [8 5]
 [2 7]]

Shape:	(3, 2)
Rank:	2



In [6]:
H = np.array([2,6,1,3,4])
describe_mat(H)

Matrix:
[2 6 1 3 4]

Shape:	(5,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.

### According to shape

### Row and Column Matrices


Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1\times j$ and column matrices would be $i\times 1$

In [7]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 4, -8, -5
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,4,-8,-5]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

Matrix:
[ 1  4 -8 -5]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  4 -8 -5]]

Shape:	(1, 4)
Rank:	2



In [8]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [1],
    [2]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [1]
 [2]]

Shape:	(3, 1)
Rank:	2



### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i= j$. We can tweak our matrix descriptor function to determine square matrices.

In [9]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [10]:
square_mat = np.array([
    [9,2,1],
    [1,0,7],
    [3,2,6]
])

non_square_mat = np.array([
    [5,2,2],
    [1,1,2]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[9 2 1]
 [1 0 7]
 [3 2 6]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[5 2 2]
 [1 1 2]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## According to element values

### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [11]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [12]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrix
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [13]:
zero_mat_row = np.zeros((1,3))
zero_mat_sqr = np.zeros((2,3))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Ones Matrix
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [14]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,3))
ones_mat_rct = np.ones((3,1))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangular Matrix: 
[[1.]
 [1.]
 [1.]]


### Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [15]:
np.array([
    [3,0,0],
    [0,2,0],
    [0,0,6]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [16]:
d = np.diag([1,4,8,5])
#d.shape[0] == d.shape[1]
d

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 5]])

### Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [17]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [19]:
np.array([
    [1,4,8,5],
    [0,4,0,8],
    [1,1,2,7],
    [1,1,1,4]
])

array([[1, 4, 8, 5],
       [0, 4, 0, 8],
       [1, 1, 2, 7],
       [1, 1, 1, 4]])

In [20]:
F = np.array([
              [1, -4, 8, -5, 9],
              [1, -4, 8, -5, 9],
              [1, -4, 8, -5, 9],
              [1, -4, 8, -5, 9],
              [1, -4, 8, -5, 9],
])
np.triu(F)


array([[ 1, -4,  8, -5,  9],
       [ 0, -4,  8, -5,  9],
       [ 0,  0,  8, -5,  9],
       [ 0,  0,  0, -5,  9],
       [ 0,  0,  0,  0,  9]])

### Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.

In [21]:
np.tril(F)

array([[ 1,  0,  0,  0,  0],
       [ 1, -4,  0,  0,  0],
       [ 1, -4,  8,  0,  0],
       [ 1, -4,  8, -5,  0],
       [ 1, -4,  8, -5,  9]])

In [22]:
np.array([
    [3,2,6],
    [9,2,1],
    [5,0,6]
])

array([[3, 2, 6],
       [9, 2, 1],
       [5, 0, 6]])

### Practice

1.Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 3k + 2m - 6s$$

$$
\theta=\begin{bmatrix} 3 & 2 & -6 \end{bmatrix}
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix}
$$

3.Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [23]:
G = np.array([
    [1,1,2],
    [9,2,1],
    [3,2,6]
])

$$
G = \left\{\begin{array}
1x_1 + 1x_2 +2x_3\\
9x_1 + 2x_2 + 1x_3\\
3x_1 + 2x_2 + 6x_3
\end{array}\right.
$$

4.Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [24]:
H = np.tril(G)
H

array([[1, 0, 0],
       [9, 2, 0],
       [3, 2, 6]])

$$
H = \left\{\begin{array}
1x_1 \\
9x_1 + 2x_2\\
3x_1 + 2x_2 + 6x_3
\end{array}\right.
$$

## Matrix Algebra

## Addition

In [25]:
A = np.array([
    [2,1],
    [2,7],
    [1,2]
])
B = np.array([
    [8,8],
    [9,9],
    [9,4]
])
A+B

array([[10,  9],
       [11, 16],
       [10,  6]])

In [26]:
2+A ##Broadcating
# 2*np.ones(A.shape)+A

array([[4, 3],
       [4, 9],
       [3, 4]])

### Subtraction

In [27]:
A-B

array([[-6, -7],
       [-7, -2],
       [-8, -2]])

In [28]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [29]:
A*B

array([[16,  8],
       [18, 63],
       [ 9,  8]])

In [30]:
2*A

array([[ 4,  2],
       [ 4, 14],
       [ 2,  4]])

In [31]:
A@B

ValueError: ignored

In [32]:
alpha=10**-10
A/(alpha+B)

array([[0.25      , 0.125     ],
       [0.22222222, 0.77777778],
       [0.11111111, 0.5       ]])

In [33]:
np.add(A,B)

array([[10,  9],
       [11, 16],
       [10,  6]])

## Activity

### Task 1
Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [34]:
## Function Area
def mat_desc(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs it Square: {is_square}\n')
  else:
    print('\nMatrix is null\n\n')

In [35]:
## Matrix Declarations
O = np.array([
    [1, 4, 8, 5],
    [1, 1, 2, 7],
    [0, 4, 1, 2]
])

P = np.array([
    [3, 2, 6],
    [8, 1, 3],
    [1, 1, 4],
    [5, 2, 2]
])

null_mat = np.array([])

R = np.array([
    [7, 7, 7],
    [7, 7, 7],
    [7, 7, 7]
])

S = np.array([
    [8, 8, 8, 8],
    [8, 8, 8, 8],
    [8, 8, 8, 8],
    [8, 8, 8, 8]
])

In [36]:
## Test Areas
mat_desc(O)

mat_desc(P)

mat_desc(null_mat)

mat_desc(R)

mat_desc(S)

Matrix:
[[1 4 8 5]
 [1 1 2 7]
 [0 4 1 2]]

Shape:	(3, 4)
Rank:	2
Is it Square: False

Matrix:
[[3 2 6]
 [8 1 3]
 [1 1 4]
 [5 2 2]]

Shape:	(4, 3)
Rank:	2
Is it Square: False


Matrix is null


Matrix:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Shape:	(3, 3)
Rank:	2
Is it Square: True

Matrix:
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]

Shape:	(4, 4)
Rank:	2
Is it Square: True



### Task 2
Create a function named `mat_operations()` that takes in two matrices an input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the difference of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [37]:

print("Enter Row and Column Size of 1st Matrix: ", end="")
rowOne = int(input())
colOne = int(input())
print("Enter Row and Column Size of 2nd Matrix: ", end="")
rowTwo = int(input())
colTwo = int(input())

if rowOne==rowTwo and colOne==colTwo:
    mat_addOne = []
    print("\nEnter " +str(rowOne*colOne)+ " Elements for 1st Matrix: ")
    for i in range(rowOne):
        mat_addOne.append([])
        for j in range(colOne):
            num = int(input())
            mat_addOne[i].append(num)

    mat_addTwo = []
    print("\nEnter " +str(rowTwo*colTwo)+ " Elements for 2nd Matrix: ")
    for i in range(rowTwo):
        mat_addTwo.append([])
        for j in range(colTwo):
            num = int(input())
            mat_addTwo[i].append(num)

    mat_addThree = []
    for i in range(rowOne):
        mat_addThree.append([])
        for j in range(colTwo):
            mat_addThree[i].append(mat_addOne[i][j]+mat_addTwo[i][j])

    print("\nAddition Result:")
    for i in range(rowOne):
        for j in range(colOne):
            print(mat_addThree[i][j], end=" ")
        print()
else:
    print("\nHuy, cannot be!! Dimension Error!")

Enter Row and Column Size of 1st Matrix: 4
4
Enter Row and Column Size of 2nd Matrix: 4
4

Enter 16 Elements for 1st Matrix: 
6
7
5
3
4
22
12
54
09
83
25
53
53
12
64
99

Enter 16 Elements for 2nd Matrix: 
99
88
77
66
55
44
33
22
11
31
24
35
46
57
68
79

Addition Result:
105 95 82 69 
59 66 45 76 
20 114 49 88 
99 69 132 178 


In [38]:
print("Enter Row and Column Size of 1st Matrix: ", end="")
rowOne = int(input())
colOne = int(input())
print("Enter Row and Column Size of 2nd Matrix: ", end="")
rowTwo = int(input())
colTwo = int(input())

if rowOne==rowTwo and colOne==colTwo:
    mat_subOne = []
    print("\nEnter " +str(rowOne*colOne)+ " Elements for 1st Matrix: ")
    for i in range(rowOne):
        mat_subOne.append([])
        for j in range(colOne):
            num = int(input())
            mat_subOne[i].append(num)

    mat_subTwo = []
    print("\nEnter " +str(rowTwo*colTwo)+ " Elements for 2nd Matrix: ")
    for i in range(rowTwo):
        mat_subTwo.append([])
        for j in range(colTwo):
            num = int(input())
            mat_subTwo[i].append(num)

    mat_subThree = []
    for i in range(rowOne):
        mat_subThree.append([])
        for j in range(colTwo):
            mat_subThree[i].append(mat_subOne[i][j]-mat_subTwo[i][j])

    print("\nSubtraction Result:")
    for i in range(rowOne):
        for j in range(colOne):
            print(mat_subThree[i][j], end=" ")
        print()
else:
    print("\nSomething is wrong hmm. There is a dimension error.")

Enter Row and Column Size of 1st Matrix: 44
4
Enter Row and Column Size of 2nd Matrix: 4
4

Something is wrong hmm. There is a dimension error.


In [39]:
print("Enter the Row Size of 1st Matrix: ", end="")
try:
    rOne = int(input())
    print("Enter the Column Size of 1st Matrix: ", end="")
    try:
        cOne = int(input())
        print("Enter " +str(rOne * cOne)+ " Elements: ", end="")
        mat_multOne = []
        for i in range(rOne):
            mat_multOne.append([])
            for j in range(cOne):
                try:
                    num = int(input())
                    mat_multOne[i].append(num)
                except ValueError:
                    print("\nCheck again!! Invalid Input!")
                    exit()
        print("\nEnter Row Size of 2nd Matrix: ", end="")
        try:
            rTwo = int(input())
            if cOne == rTwo:
                print("Enter Column Size of Second Matrix: ", end="")
                try:
                    cTwo = int(input())
                    print("Enter " +str(rTwo * cTwo)+ " Elements: ", end="")
                    mat_multTwo = []
                    for i in range(rTwo):
                        mat_multTwo.append([])
                        for j in range(cTwo):
                            try:
                                num = int(input())
                                mat_multTwo[i].append(num)
                            except ValueError:
                                print("\nCheck again!! Invalid Input!")
                                exit()

                    mat_multThree = []
                    for i in range(rOne):
                        mat_multThree.append([])
                        for j in range(cTwo):
                            sum = 0
                            for k in range(cOne):
                                sum = sum + (mat_multOne[i][k] * mat_multTwo[k][j])
                            mat_multThree[i].append(sum)

                    print("\nMultiplication Result of Two Given Matrix is:")
                    for i in range(rOne):
                        for j in range(cTwo):
                            print(mat_multThree[i][j], end=" ")
                        print()
                except ValueError:
                    print("\nCheck again!! Invalid Column Size!")
            else:
                print("\nCheck again!! Multiplication not possible!")
        except ValueError:
            print("\nCheck Again!! Invalid Row Size!")
    except ValueError:
        print("\nCheck again!! Invalid Column Size!")
except ValueError:
    print("\nCheck again!! Invalid Row Size!")

Enter the Row Size of 1st Matrix: 4
Enter the Column Size of 1st Matrix: 4
Enter 16 Elements: 100
102
103
109
111
123
678
863
123
24
356
234
543
72
52
13

Enter Row Size of 2nd Matrix: 4
Enter Column Size of Second Matrix: 4
Enter 16 Elements: 1
2
3
4
5
6
7
8
9
0
11
22
33
44
55
56

Multiplication Result of Two Given Matrix is:
5134 5608 8142 9586 
35307 38932 56117 64672 
11169 10686 17323 21620 
1800 2090 3420 4620 
